# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: School-OS
description: Custom OS for school environment with restricted access and Flatpak control.

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  # -------------------------------------------------------------------------
  # MODULE 1: FILES - Essential for Polkit rules and configuration
  # -------------------------------------------------------------------------
  - type: files
    files:
      - source: system
        destination: /
      - source: files/etc/polkit-1/rules.d/50-no-user-flatpak.rules
        destination: /etc/polkit-1/rules.d/50-no-user-flatpak.rules

  # -------------------------------------------------------------------------
  # MODULE 2: DNF - Custom Installs and Removals
  # -------------------------------------------------------------------------
  - type: dnf
    install:
      packages:
        # NEW: Ensure Fish shell is installed (layered)
        - fish

    remove:
      packages:
        # Standard removal of the RPM version of Firefox
        - firefox
        - firefox-langpacks
        # Previous list of RPMs to remove (Note: 'fish' is removed from this list)
        - kde-partitionmanager
        - fcitx5
        - fcitx5-autostart
        - input-remapper
        - kfind
        - zsh # Keeping zsh removed
        - rclone
        - restic
        - libratbagd
        - openrazer-daemon
        - khelpcenter
        - kinfocenter
        - drkonqi-coredump-gui
        - kdebugsettings

        # Applications to remove from the RPM Layer
        - kjournalbrowser
        - ksystemlog
        - plasma-systemmonitor
        - kbd-layout-viewer-5

  # -------------------------------------------------------------------------
  # MODULE 3: RPM-OSTREE - Removals (Leaving this module commented out as before)
  # -------------------------------------------------------------------------
  #- type: rpm-ostree
  #  remove:
  #
  #
  # -------------------------------------------------------------------------
  # MODULE 4: FLATPAKS - Installing your list and REMOVING ALL THE OTHERS
  # -------------------------------------------------------------------------
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (System)
          url: https://flathub.org/repo/flathub.flatpakrepo

        # This list defines the ONLY Flatpaks that will be present system-wide.
        install:
          # Your essential applications
          - org.mozilla.firefox
          - org.onlyoffice.desktopeditors
          - org.gnome.Loupe
          # Teams client replacement
          - com.github.IsmaelMartinez.teams_for_linux

        # This list targets all unwanted desktop applications that are pre-installed as Flatpaks.
        remove:
          # Applications from your previous comprehensive list
          - org.kde.ktailctl
          - io.flattool.Warehouse
          - com.github.micahflee.incus.InputLeap
          - io.github.pwr_solaar.solaar
          - org.gnome.DejaDup
          - org.gnome.FontDownloader
          - org.gnome.clocks
          - org.kde.filelight
          - org.kde.gwenview
          - org.kde.partitionmanager
          - org.kde.kweather
          - org.kde.kate
          - org.kde.konsole
          - org.kde.kontact
          - org.kde.okular
          - com.visualstudio.code.oss
          - com.vscodium.codium.insiders

          # New removals
          - org.kde.kdeconnect
          - org.kde.knetattach
          - com.valvesoftware.Steam.Utility.sunshine
          - org.kde.plasma_emojier

      - scope: user
        notify: false
