# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: School-OS
description: Custom OS for school environment with essential tools.

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      # System-wide Flathub packages (all users get these)
      - notify: true
        scope: system
        repo:
          title: Flathub (System)
          url: https://flathub.org/repo/flathub.flatpakrepo
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.onlyoffice.desktopeditors
          - org.libreoffice.LibreOffice
      # User-scoped repositories (optional - for future user-specific apps)
      - scope: user
        notify: false

  - type: signing
